# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TbtNavigation' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for TbtNavigation
  
  pod 'MapboxNavigation', '~> 0.22.0'
  
  target 'TbtNavigationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TbtNavigation-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TbtNavigation-tvOS

  target 'TbtNavigation-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
